// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvuoycrfqiktuqxnsmmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dW95Y3JmcWlrdHVxeG5zbW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQ1MjEsImV4cCI6MjA2NTU1MDUyMX0.mPW9fKT8PrRf_52G_Ais2AoFqi-aWQ0m45JmtqhGy6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);